Refuse to run if no ucodes.

diff --git a/root/etc/init.d/start_lcars b/root/etc/init.d/start_lcars
--- a/root/etc/init.d/start_lcars
+++ b/root/etc/init.d/start_lcars
@@ -2,4 +2,17 @@
 
 # $Id$
 
-lcars > /dev/null
+# lcars silently fails if ucodes are missing. Therefore refuse to run
+# in that case. 
+
+# This code is for dBox only.
+
+if [ -e /var/tuxbox/ucodes/cam-alpha.bin \
+     -a  \(    -e /var/tuxbox/ucodes/avia500.ux \
+            -o -e /var/tuxbox/ucodes/avia600.ux \) ] ; then
+    lcars
+else
+    echo ""
+    echo "Ucodes are missing. Exiting."
+    exit 1
+fi
